### ISSUE TITLE
Return raw query instead of execute it

### ISSUE THREAD

**Issue by 7633** [sacrud/sacrud#108]
I suppose this behavior appear recently, may be after sqlalchemy update.

Sqlalchemy: 1.1.12
python: 3.5.3

Command `result = session.sacrud(MyTable).read()` returns me Query object:
`SELECT mytable.id AS mytable_id, mytable.name AS mytable_name
FROM mytable` 
instead of executing them and return result.

I have to add `.all()` at the end of my command to get expected result.

**Comment by uralbash** [comment]
This is normal behavior of ``sacrud`` (see examples https://github.com/sacrud/sacrud/blob/master/tests/test_action.py#L25-L103). ``all()`` is not substituted so that it can be used in subqueries. Probably need to add the method ``read_all()`` to avoid confusion.

**Comment by 7633** [comment]
No, I think it's not neccessary. Now this behaviour is obvious
